level:
    '1': 
        - _TOKEN_MAP_
        - _IGNORE_
        - _SPACY_
        - PHONE
        - PERSON
        - ADDRESS
        - CCARD
        - MONEY
        - SSN
        - PIN
    '2':
        - _TOKEN_MAP_
        - _IGNORE_
        - _SPACY_
        - PHONE
        - PERSON
        - ADDRESS
        - CCARD
        - MONEY
        - LOC
        - EMAIL
        - SSN
        - ZIP
        - PIN
    '3':
        - _TOKEN_MAP_
        - _IGNORE_
        - _SPACY_
        - PHONE
        - PERSON
        - ADDRESS
        - CCARD
        - MONEY
        - LOC
        - CARDINAL
        - DATE
        - EVENT
        - FAC
        - GPE
        - LANGUAGE
        - LAUGHTER
        - LAW
        - NORP
        - ORG
        - ORDINAL
        - PERCENT
        - PRODUCT
        - QUANTITY
        - TIME
        - WORK_OF_ART
        - ZIP
        - SSN
        - EMAIL
        - PIN

always-anonymize:
    - _IGNORE_

always-redact:
    - _TOKEN_MAP_

redaction-order:
    - _TOKEN_MAP_
    - _IGNORE_
    - PERSON
    - ADDRESS
    - CCARD
    - PHONE
    - SSN
    - ZIP
    - EMAIL
    - MONEY
    - LOC
    - DATE
    - EVENT
    - FAC
    - GPE
    - LANGUAGE
    - LAUGHTER
    - LAW
    - NORP
    - ORG
    - PERCENT
    - PRODUCT
    - QUANTITY
    - TIME
    - WORK_OF_ART
    - PIN
    - _SPACY_
    - ORDINAL
    - CARDINAL

anon-map: {}

token-map: {}