level:
    '1': 
        - _IGNORE_
        - _SPACY_
        - PHONE
        - PERSON
        - ADDRESS
        - CCARD
        - MONEY
        - SSN
        - PIN
    '2':
        - _IGNORE_
        - _SPACY_
        - PHONE
        - PERSON
        - ADDRESS
        - CCARD
        - MONEY
        - LOC
        - EMAIL
        - SSN
        - ZIP
        - PIN
    '3':
        - _IGNORE_
        - _SPACY_
        - PHONE
        - PERSON
        - ADDRESS
        - CCARD
        - MONEY
        - LOC
        - CARDINAL
        - DATE
        - EVENT
        - FAC
        - GPE
        - LANGUAGE
        - LAUGHTER
        - LAW
        - NORP
        - ORG
        - ORDINAL
        - PERCENT
        - PRODUCT
        - QUANTITY
        - TIME
        - WORK_OF_ART
        - ZIP
        - SSN
        - EMAIL
        - PIN

always-anonymize:
    - _IGNORE_

redaction-order:
    - _IGNORE_
    - PERSON
    - ADDRESS
    - CCARD
    - PHONE
    - SSN
    - ZIP
    - EMAIL
    - MONEY
    - LOC
    - DATE
    - EVENT
    - FAC
    - GPE
    - LANGUAGE
    - LAUGHTER
    - LAW
    - NORP
    - ORG
    - PERCENT
    - PRODUCT
    - QUANTITY
    - TIME
    - WORK_OF_ART
    - PIN
    - _SPACY_
    - ORDINAL
    - CARDINAL

anon-map:
    ADDRESS: [ ADDRESS, streetAddress ]
    CARDINAL: [ CARDINAL, digits, DIGITS ]
    CCARD: [ CCARD, creditCardNumber, ccNum ]
    CREDENTIALS: [ CREDENTIALS, credentials ]
    DATE: [ DATE, expDate ]
    EMAIL: [ EMAIL, EMAIL_ADDRESS, emailAddress ]
    IPADDRESS: [ IPADDRESS, ipAddress ]
    PASSWORD: [ PASSWORD, password ]
    PHONE: [ PHONE, PHONE_NUMBER, phoneNumber ]
    SSN: [ SSN, usSocialSecurityNumber ]
    USERNAME: [ USERNAME, username ]
    ZIP: [ ZIP, zipcode ]

token-map:
    ZIP: [ "<ZIP\/>" ]
    PIN: [ "<PIN\/>", "<CVV\/>" ]
    CCARD: [ "<ccNum\/>" ]
    DATE: [ "<expDate\/>" ]